workflows:
  react-native:
    name: React Native Workflow
    scripts:
      - name: Install dependencies
        script: yarn install
      - name: Build Android release
        script: cd android && ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/app-release.apk
